---
title: "GDHY_ts"
author: "Raed Hamed"
date: "22-5-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GDHY_ts

The main properties of this script is to prepare and post-process the GDHY global gridded crop yield data into detrended spatial averaged time series. Summary statistics and associated plots are generated. 

```{r clean workspace, include=FALSE}
rm(list = ls())
graphics.off()
gc()
```

```{r packages, data and functions, echo=True, include=FALSE}
#Load packages and datasets:

library("tidyverse")
library("raster")
library("ncdf4")
library("rasterVis")
library("USAboundaries")
library("SDMTools")
library("maptools")
library("RColorBrewer")
library("sf")

##Lib for clustering
library("dbscan")
library("fpc")
library("factoextra")

data(wrld_simpl)
mapTheme <- rasterTheme(region=brewer.pal(10, "RdYlBu"))
mapTheme_harvest <- rasterTheme(region=rev(brewer.pal(10, "RdYlGn")))
mapTheme_Yield <- rasterTheme(region=brewer.pal(10, "RdYlGn"))


```

```{r set directory, echo=FALSE}
dir_in    <-"C:/Users/rhd630/Desktop/PhD/Academic/Modelling/Input_data/"  
dir_GHDY  <- paste0(dir_in,"/GDHY/soybean") 
dir_micra <- paste0(dir_in,"/MIRCA2000")
```

```{r Load Yield Dataset, echo=FALSE}

nc_list_yield <- list.files(dir_GHDY) #list files in dias directory
#-----------------------------------------------------------------------------------------------------------
#read nc files into raster bricks
nc_bricklist_yield <- list() 
for(i in 1:length(nc_list_yield)){ 
  nc_bricklist_yield[[i]] <- brick(paste0(dir_GHDY,"/",nc_list_yield[[i]])) 
} 
#-----------------------------------------------------------------------------------------------------------
#stack files
nc_stack_yield <- stack(nc_bricklist_yield)    
#Adjust extent
nc_stack_yield <-raster::rotate(nc_stack_yield)

```

```{r Load Mirca Dataset, echo=FALSE}
#### Load Mirca maps
file_asc_gz_mirca_irc <-file.path(dir_micra,'annual_area_harvested_irc_crop08_ha_30mn.asc.gz')   
file_asc_gz_mirca_rfc <-file.path(dir_micra,'annual_area_harvested_rfc_crop08_ha_30mn.asc.gz')
#-----------------------------------------------------------------------------------------------------------
mirca_irc <-read.asc.gz(file_asc_gz_mirca_irc)
mirca_rfc <-read.asc.gz(file_asc_gz_mirca_rfc)
#-----------------------------------------------------------------------------------------------------------
#Irrigated harvested soybean area
mirca_irc_raster <-raster(mirca_irc)
#Rainfed harvested soybean area
mirca_rfc_raster <-raster(mirca_rfc)
```

```{r Process and plot Mirca Dataset, echo=FALSE}
total_harvested_area <- mirca_irc_raster +  mirca_rfc_raster
fraction_rf_to_ir <-mirca_rfc_raster/total_harvested_area


mask(log10(mirca_irc_raster) ,log10(mirca_irc_raster) > 0 , maskvalue=FALSE) + mask(log10(mirca_rfc_raster) ,log10(mirca_rfc_raster) > 0 , maskvalue=FALSE) 


plot_fraction_rf_to_ir <- levelplot(fraction_rf_to_ir,
                   margin=F,
                   par.settings=mapTheme,
                   main="Global pattern of the degree of rainfed harvested area for soybeans")

plot_fraction_rf_to_ir + latticeExtra::layer(sp.lines(wrld_simpl[wrld_simpl@data$UN!="10",], col="gray30", lwd=0.5)) 
```

```{r Harvested Area according to Mirca Dataset, echo=FALSE}
#Soybeans harvested area over rainfed regions
#Area classified as rainfed when at least 90% of the area share is rainfed (see Schauberger et al.2017)
rainfed_harvest_90 <- mask(mirca_rfc_raster, fraction_rf_to_ir >= 0.9, maskvalue=FALSE) 
log_rainfed_harvest_90 <-mask(log10(rainfed_harvest_90),log10(rainfed_harvest_90) >= 1,maskvalue=FALSE )

plot_harvest_rainfed <- levelplot(log_rainfed_harvest_90,
                   margin=F,
                   par.settings=mapTheme_harvest,
                   main="Soybeans harvested area over rainfed regions (ha) (log10)",
                   sub="Area classified as rainfed when at least 90% of the area share is rainfed (see Schauberger et al.2017)")

plot_harvest_rainfed + latticeExtra::layer(sp.lines(wrld_simpl[wrld_simpl@data$UN!="10",], col="gray30", lwd=0.5)) 

```

```{r Harvested Area according to Mirca Dataset for the US, echo=FALSE, warning=TRUE}
#-----------------------------------------------------------------------------------------------------------
usa_states <- as_Spatial(st_geometry(us_states()))
states_ommit <-as_Spatial(st_geometry(us_states(state = c("AK","HI","PR"))))
states_of_interest <-as_Spatial(st_geometry(us_states(state = c("MN","IL","IA","IN","NE","OH"))))
states_of_interest_long <-as_Spatial(st_geometry(us_states(state = c("MN","IL","IA","IN","NE","OH","SD","ND","MO","AR"))))

spatial_usa <-usa_states-states_ommit
#-----------------------------------------------------------------------------------------------------------
log_rainfed_harvest_90_US <-crop(log_rainfed_harvest_90, spatial_usa) 
log_rainfed_harvest_90_US <-mask(log_rainfed_harvest_90_US, spatial_usa) 
#-----------------------------------------------------------------------------------------------------------
plot_rainfed_yield_US <- levelplot(mean(log_rainfed_harvest_90_US),
                   margin=F,
                   par.settings=mapTheme_harvest,
                   main="Soybeans harvested area over rainfed regions in the US (ha) (log10)",
                   sub="Area classified as rainfed when at least 90% of the area share is rainfed (see Schauberger et al.2017)")

plot_rainfed_yield_US + latticeExtra::layer(sp.lines(spatial_usa, col="gray30", lwd=0.5)) +latticeExtra::layer(sp.lines(states_of_interest_long, col="midnightblue",lwd=2))



```

```{r selecting cropping system and geographical area, echo=FALSE, warning=FALSE}

rainfed_Yield_GDHY <-mask(nc_stack_yield, fraction_rf_to_ir >= 0.9, maskvalue =FALSE) 
#rainfed_Yield_GDHY <-mask(rainfed_Yield_GDHY, mirca_rfc_raster > 10000, maskvalue =FALSE) 

#-----------------------------------------------------------------------------------------------------------
usa_states <- as_Spatial(st_geometry(us_states()))
states_ommit <-as_Spatial(st_geometry(us_states(state = c("AK","HI","PR"))))
states_of_interest <-as_Spatial(st_geometry(us_states(state = c("MN","IL","IA","IN","NE","OH"))))
spatial_usa <-usa_states-states_ommit
crs(spatial_usa) <- crs(rainfed_Yield_GDHY)
#-----------------------------------------------------------------------------------------------------------
rainfed_Yield_GDHY_US <-crop(rainfed_Yield_GDHY, spatial_usa) 
rainfed_Yield_GDHY_US <-mask(rainfed_Yield_GDHY_US, spatial_usa) 
#-----------------------------------------------------------------------------------------------------------
```

```{r different functions for removing trend, echo=FALSE, warning=TRUE}
time <- 1:nlayers(rainfed_Yield_GDHY_US)
#https://stackoverflow.com/questions/53054316/remove-linear-trend-from-raster-stack-r
get_residuals <- function(x) {
 if (any(is.na(x[time]))){
    rep(NA, length(x)) } 
  else {
    m <- lm(x~time)
    q <- residuals(m)
    return(q)
  }
}
#-----------------------------------------------------------------------------------------------------------
first_diff <- function(x) {
 if (any(is.na(x[time]))){
    rep(NA, length(x)) } 
  else {
    diff = x-lag(x)
    return(diff)
  }
}

```

```{r Apply functions and plot, echo=FALSE, warning=TRUE}
lin_detr_rainfed_Yield_GDHY_US <- calc(rainfed_Yield_GDHY_US,get_residuals) # Create our residual (detrended) time series stack
first_diff_rainfed_Yield_GDHY_US <- calc(rainfed_Yield_GDHY_US, first_diff)   

Vector_of_years <- as.character(1981:2016)
names(lin_detr_rainfed_Yield_GDHY_US) <- Vector_of_years


plot_rainfed_yield_US_lin_detr <- levelplot(lin_detr_rainfed_Yield_GDHY_US,
                   margin=F,
                   par.settings=mapTheme_Yield,
                   main="Soybeans anomalies",
                   sub="Based on residuals after removing the slope and the intercept")

plot_rainfed_yield_US_lin_detr  + latticeExtra::layer(sp.lines(spatial_usa, col="gray30", lwd=0.5)) +latticeExtra::layer(sp.lines(states_of_interest_long, col="maroon", lwd=1.5))



plot_rainfed_yield_US_first_diff <- levelplot(first_diff_rainfed_Yield_GDHY_US,
                   margin=F,
                   par.settings=mapTheme_Yield,
                   main="Soybeans anomalies",
                   sub="Based on first differences")

plot_rainfed_yield_US_first_diff + latticeExtra::layer(sp.lines(spatial_usa, col="gray30", lwd=0.5)) +latticeExtra::layer(sp.lines(states_of_interest_long, col="maroon", lwd=1.5))

```


```{r Clustering attempts, echo=FALSE, warning=TRUE}
library(cluster)
# Extract all values from the raster into a data frame
rstDF <- values(rainfed_Yield_GDHY_US)

# Check NA's in the data
idx <- complete.cases(rstDF)

# Initiate the raster datasets that will hold all clustering solutions 
# from 2 groups/clusters up to 12
rstKM <- raster(rainfed_Yield_GDHY_US[[1]])
rstCLARA <- raster(rainfed_Yield_GDHY_US[[1]])



for(nClust in 2:12){
  
  cat("-> Clustering data for nClust =",nClust,"......")
  
  # Perform K-means clustering
  km <- kmeans(rstDF[idx,], centers = nClust, iter.max = 50)
  
  # Perform CLARA's clustering (using manhattan distance)
  cla <- clara(rstDF[idx, ], k = nClust, metric = "manhattan")
  
  # Create a temporary integer vector for holding cluster numbers
  kmClust <- vector(mode = "integer", length = ncell(rainfed_Yield_GDHY_US))
  claClust <- vector(mode = "integer", length = ncell(rainfed_Yield_GDHY_US))
  
  # Generate the temporary clustering vector for K-means (keeps track of NA's)
  kmClust[!idx] <- NA
  kmClust[idx] <- km$cluster
  
  # Generate the temporary clustering vector for CLARA (keeps track of NA's too ;-)
  claClust[!idx] <- NA
  claClust[idx] <- cla$clustering
  
  # Create a temporary raster for holding the new clustering solution
  # K-means
  tmpRstKM <- raster(rainfed_Yield_GDHY_US[[1]])
  # CLARA
  tmpRstCLARA <- raster(rainfed_Yield_GDHY_US[[1]])

  # Set raster values with the cluster vector
  # K-means
  values(tmpRstKM) <- kmClust
  # CLARA
  values(tmpRstCLARA) <- claClust
  
  # Stack the temporary rasters onto the final ones
  if(nClust==2){
    rstKM    <- tmpRstKM
    rstCLARA <- tmpRstCLARA
  }else{
    rstKM    <- stack(rstKM, tmpRstKM)
    rstCLARA <- stack(rstCLARA, tmpRstCLARA)
  }
  
  cat(" done!\n\n")
}

# Write the clustering solutions for each algorithm
writeRaster(rstKM,"C:/Users/rhd630/Desktop/PhD/Academic/Data/temp/LT8_PGNP_KMeans_nc2_12-1.tif", overwrite=TRUE)
writeRaster(rstCLARA,"C:/Users/rhd630/Desktop/PhD/Academic/Data/temp/LT8_PGNP_CLARA_nc2_12-1.tif", overwrite=TRUE)


library(clusterCrit)



# Start a data frame that will store all silhouette values
# for k-means and CLARA   
clustPerfSI <- data.frame(nClust = 2:12, SI_KM = NA, SI_CLARA = NA)


for(i in 1:nlayers(rstKM)){ # Iterate through each layer
  
  cat("-> Evaluating clustering performance for nClust =",(2:12)[i],"......")
  
  # Extract random cell samples stratified by cluster
  cellIdx_RstKM <- sampleStratified(rstKM[[i]], size = 2000)
  cellIdx_rstCLARA <- sampleStratified(rstCLARA[[i]], size = 2000)
  
  # Get cell values from the Stratified Random Sample from the raster 
  # data frame object (rstDF)
  rstDFStRS_KM <- rstDF[cellIdx_RstKM[,1], ]
  rstDFStRS_CLARA <- rstDF[cellIdx_rstCLARA[,1], ]
  
  # Make sure all columns are numeric (intCriteria function is picky on this)
  rstDFStRS_KM[] <- sapply(rstDFStRS_KM, as.numeric)
  rstDFStRS_CLARA[] <- sapply(rstDFStRS_CLARA, as.numeric)
  
  # Compute the sample-based Silhouette index for: 
  #    
  # K-means
  clCritKM <- intCriteria(traj = rstDFStRS_KM, 
                          part = as.integer(cellIdx_RstKM[,2]), 
                          crit = "Silhouette")
  # and CLARA
  clCritCLARA <- intCriteria(traj = rstDFStRS_CLARA, 
                             part = as.integer(cellIdx_rstCLARA[,2]), 
                             crit = "Silhouette")

  # Write the silhouette index value to clustPerfSI data frame holding 
  # all results
  clustPerfSI[i, "SI_KM"]    <- clCritKM[[1]][1]
  clustPerfSI[i, "SI_CLARA"] <- clCritCLARA[[1]][1]
  
  cat(" done!\n\n")
  
}

write.csv(clustPerfSI, file = "C:/Users/rhd630/Desktop/PhD/Academic/Data/temp/clustPerfSI.csv", row.names = FALSE)
knitr::kable(clustPerfSI, digits = 3, align = "c", 
             col.names = c("#clusters","Avg. Silhouette (k-means)","Avg. Silhouette (CLARA)"))


plot(clustPerfSI[,1], clustPerfSI[,2], 
     xlim = c(1,13), ylim = range(clustPerfSI[,2:3]), type = "n", 
     ylab="Avg. Silhouette Index", xlab="# of clusters",
     main="Silhouette index by # of clusters")

# Plot Avg Silhouette values across # of clusters for K-means
lines(clustPerfSI[,1], clustPerfSI[,2], col="red")
# Plot Avg Silhouette values across # of clusters for CLARA
lines(clustPerfSI[,1], clustPerfSI[,3], col="blue")

# Grid lines
abline(v = 1:13, lty=2, col="light grey")
abline(h = seq(0.30,0.44,0.02), lty=2, col="light grey")

legend("topright", legend=c("K-means","CLARA"), col=c("red","blue"), lty=1, lwd=1)

plot_rainfed_yield_US_KM_Clustering<- levelplot(rstCLARA[[5]],
                   margin=F,
                   par.settings=mapTheme_Yield,
                   main="K mean 6 clusters",
                   sub="Based on linear detrending")

plot_rainfed_yield_US_KM_Clustering + latticeExtra::layer(sp.lines(spatial_usa, col="gray30", lwd=0.5)) +latticeExtra::layer(sp.lines(states_of_interest_long, col="maroon", lwd=1.5))

###########DBSCAN
library(fossil)

r<-rainfed_Yield_GDHY_US[[32]] #my raster taken from a first layer of a stack
    rlon<-rlat<-r #copy r to rlon and rlat rasters [1]][1]which will contain the longitude and latitude
    xy<-xyFromCell(r,1:length(r)) #matrix of logitudes (x) and latitudes(y)
    rlon[]<-xy[,1] #raster of longitudes
    rlat[]<-xy[,2] #raster of latitides
    
    
    
inputdata <-(data.frame(long=rlon[], lat=rlat[], RecordID=values(rainfed_Yield_GDHY_US[[32]])))
idx <-complete.cases(inputdata)
d = earth.dist(inputdata[idx,], dist = TRUE) 
ds <- dbscan(d,eps = 0.5,MinPts = 10, method = "dist")
```
